name: DigiCert Code Scan
on: workflow_dispatch
jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - name: Run DigiCert Code Scan composite action
        uses: digicert/digicert-code-monitoring-action@master
        with:
          host: https://one.stage.az.digicert.net
          api-key: ${{ secrets.DIGICERT_BACKEND_API_KEY }}
